Repository BlueBrain/nexus, pull requests merged in 2019-02, with the labels that each got.

#415 Automate documentation deployment in Jenkinsfile
  Jenkinsfile
Labels: review

#416 Add link to sandbox
  Jenkinsfile
  src/main/paradox/docs/getting-started/running-nexus/index.md
  src/main/paradox/docs/getting-started/running-nexus/on-premise-cloud.md
Labels: review

#369 Release notes for Nexus Web
  src/main/paradox/docs/release-notes/assets/img/nexus-js-logo.png
  src/main/paradox/docs/release-notes/assets/img/nexus-web.png
  src/main/paradox/docs/release-notes/index.md
Labels: documentation, nexus-sdk-js, nexus-web, review

#308 Added short paragraph to Nexus documentation
  src/main/paradox/docs/getting-started/index.md
  src/main/paradox/docs/getting-started/nexus-concepts.md
Labels: documentation, review

#431 Added references to the Python SDK and the CLI.
  src/main/paradox/docs/release-notes/index.md
Labels: review

#426 Documentation about Nexus Web and JS SDK
  src/main/paradox/docs/index.md
  src/main/paradox/docs/release-notes/index.md
  src/main/paradox/docs/tools/assets/img/nexus-js-logo.png
  src/main/paradox/docs/tools/index.md
  src/main/paradox/docs/webapps/assets/img/clone-query.png
  src/main/paradox/docs/webapps/assets/img/copy-token.gif
  src/main/paradox/docs/webapps/assets/img/create-organization-button.png
  src/main/paradox/docs/webapps/assets/img/create-organization.png
  src/main/paradox/docs/webapps/assets/img/create-project-button.png
  src/main/paradox/docs/webapps/assets/img/create-project.png
  src/main/paradox/docs/webapps/assets/img/create-resource-button.png
  src/main/paradox/docs/webapps/assets/img/create-resource.png
  src/main/paradox/docs/webapps/assets/img/edit-organization-button.png
  src/main/paradox/docs/webapps/assets/img/edit-organization.png
  src/main/paradox/docs/webapps/assets/img/edit-project-button.png
  src/main/paradox/docs/webapps/assets/img/edit-project.png
  src/main/paradox/docs/webapps/assets/img/es-query-button.png
  src/main/paradox/docs/webapps/assets/img/es-query.png
  src/main/paradox/docs/webapps/assets/img/list-orgs.png
  src/main/paradox/docs/webapps/assets/img/list-projects.png
  src/main/paradox/docs/webapps/assets/img/list-resources.png
  src/main/paradox/docs/webapps/assets/img/login-web.png
  src/main/paradox/docs/webapps/assets/img/make-project-public.png
  src/main/paradox/docs/webapps/assets/img/new-query-button.png
  src/main/paradox/docs/webapps/assets/img/new-query.png
  src/main/paradox/docs/webapps/assets/img/search-resources.png
  src/main/paradox/docs/webapps/assets/img/sparql-query-button.png
  src/main/paradox/docs/webapps/assets/img/sparql-query.png
  src/main/paradox/docs/webapps/assets/img/view-resource.png
  src/main/paradox/docs/webapps/index.md
Labels: documentation, nexus-sdk-js, nexus-web, review

#432 Add v2 format docker-compose template
  Jenkinsfile
  src/main/paradox/docs/getting-started/running-nexus/docker-compose/docker-compose.yaml
  src/main/paradox/docs/getting-started/running-nexus/docker-swarm/docker-compose.yaml
  src/main/paradox/docs/getting-started/running-nexus/docker-swarm/nginx.conf
  src/main/paradox/docs/getting-started/running-nexus/docker.md
Labels: review

#418 Removed Postman collections
  src/main/paradox/docs/api/admin/admin-orgs-api.md
  src/main/paradox/docs/api/admin/admin-projects-api.md
  src/main/paradox/docs/api/assets/organization-postman.json
  src/main/paradox/docs/api/assets/project-postman.json
  src/main/paradox/docs/api/assets/resolvers/resolver-postman.json
  src/main/paradox/docs/api/assets/resources/resource-postman.json
  src/main/paradox/docs/api/assets/schemas/schema-postman.json
  src/main/paradox/docs/api/assets/views/view-postman.json
  src/main/paradox/docs/api/kg/kg-resolvers-api.md
  src/main/paradox/docs/api/kg/kg-resources-api.md
  src/main/paradox/docs/api/kg/kg-schemas-api.md
  src/main/paradox/docs/api/kg/kg-views-api.md
  src/main/paradox/docs/api/operating-on-resources.md
Labels: review

#442 Added ACLs explanation on relevant API sections
  src/main/paradox/docs/api/admin/admin-orgs-api.md
  src/main/paradox/docs/api/admin/admin-projects-api.md
  src/main/paradox/docs/api/assets/permissions/permissions-get-rev.json
  src/main/paradox/docs/api/assets/permissions/permissions-get.json
  src/main/paradox/docs/api/iam/iam-acls-api.md
  src/main/paradox/docs/api/iam/iam-permissions-api.md
  src/main/paradox/docs/api/iam/iam-realms-api.md
  src/main/paradox/docs/api/iam/permissions-api.md
  src/main/paradox/docs/api/kg/kg-files-api.md
  src/main/paradox/docs/api/kg/kg-resolvers-api.md
  src/main/paradox/docs/api/kg/kg-resources-api.md
  src/main/paradox/docs/api/kg/kg-schemas-api.md
  src/main/paradox/docs/api/kg/kg-views-api.md
Labels: review

#440 Added the tutorial as a section in the Getting Started Guide
  src/main/paradox/docs/getting-started/index.md
  src/main/paradox/docs/getting-started/tutorials.md
  src/main/paradox/docs/tutorial/getting-started/assets/Movielens-default_nexus_graph.png
  src/main/paradox/docs/tutorial/getting-started/quick-start/index.md
  src/main/paradox/docs/tutorial/knowledge-graph/querying-knowledge-graph.md
Labels: review

#449 Added IAM and ADMIN context and updated KG
  src/main/paradox/contexts/acls.json
  src/main/paradox/contexts/admin.json
  src/main/paradox/contexts/error.json
  src/main/paradox/contexts/iam.json
  src/main/paradox/contexts/identity.json
  src/main/paradox/contexts/realm.json
  src/main/paradox/contexts/resolver.json
  src/main/paradox/contexts/resource.json
  src/main/paradox/contexts/search.json
  src/main/paradox/contexts/view.json
  src/main/paradox/schemas/organization.json
  src/main/paradox/schemas/project.json
  src/main/paradox/schemas/resolver.json
  src/main/paradox/schemas/view.json
Labels: review

#450 Add EPFL logo to the header
  src/main/paradox/index.html
Labels: review

#454 Google Analytics to Product page and GDPR header
  src/main/paradox/index.html
Labels: review

#455 Fix Cookie Consent in product page
  src/main/paradox/index.html
Labels: review

#462 Add releaes notes
  src/main/paradox/assets/css/style.e2443695.css
  src/main/paradox/index.html
Labels: review

#464 Fix JS SDK url in documentation + 2 typos
  src/main/paradox/docs/index.md
  src/main/paradox/docs/release-notes/index.md
  src/main/paradox/docs/tools/index.md
Labels: review

#453 Changed from thread to max-connections
  src/main/paradox/docs/tutorial/getting-started/quick-start/index.md
Labels: review

#466 Updated admin-projects-api.md
  src/main/paradox/docs/api/admin/admin-projects-api.md
Labels: review

#467 Fixed typo in kg-resolvers-api.md
  src/main/paradox/docs/api/kg/kg-resolvers-api.md
Labels: review
