Repository BlueBrain/nexus, pull requests merged in 2019-03, with the labels that each got.

#463 Update nexus-concepts.md
  src/main/paradox/docs/getting-started/nexus-concepts.md
Labels: documentation

#517 Update nexus-concepts.md
  src/main/paradox/docs/getting-started/nexus-concepts.md
Labels: review

#465 Updated API Reference index.md
  src/main/paradox/docs/api/index.md
Labels: documentation, review

#468 Fixed typos in documentation
  src/main/paradox/docs/api/admin/admin-projects-api.md
  src/main/paradox/docs/api/kg/kg-resolvers-api.md
  src/main/paradox/docs/api/kg/kg-schemas-api.md
Labels: documentation, review

#521 doc: remove all "TBC" pages, keep only real doc.
  src/main/paradox/docs/additional-info/faq.md
  src/main/paradox/docs/additional-info/incremental-domain-definition.md
  src/main/paradox/docs/additional-info/index.md
  src/main/paradox/docs/architecture/index.md
  src/main/paradox/docs/getting-started/example.md
  src/main/paradox/docs/getting-started/shacl.md
Labels: review

#513 doc: Move tutorial section to top-level item, and cleanup
  src/main/paradox/docs/getting-started/index.md
  src/main/paradox/docs/getting-started/tutorials.md
  src/main/paradox/docs/index.md
  src/main/paradox/docs/tutorial/index.md
Labels: documentation, enhancement, review

#540 fix(docs): correcting URL in components page
  src/main/paradox/docs/architecture/components.md
Labels: documentation, review

#543 fix(docs): copyright years in footer
  build.sbt
Labels: review

#545 docs: Gather all deployment options in a single page
  src/main/paradox/docs/getting-started/running-nexus/docker.md
  src/main/paradox/docs/getting-started/running-nexus/index.md
  src/main/paradox/docs/getting-started/running-nexus/minikube.md
  src/main/paradox/docs/getting-started/running-nexus/on-premise-cloud.md
Labels: documentation, review

#547 Avoid Markdown processing of the Remark slides by Paradox
  src/main/paradox/docs/architecture/index.md
  src/main/paradox/docs/architecture/meetup/index.html
  src/main/paradox/docs/architecture/meetup/markdown
Labels: review

#546 docs: clean up documentation structure
  src/main/paradox/docs/additional-info/architecture/components.md
  src/main/paradox/docs/additional-info/architecture/components.png
  src/main/paradox/docs/additional-info/architecture/index.md
  src/main/paradox/docs/additional-info/architecture/integration.md
  src/main/paradox/docs/additional-info/architecture/integration.png
  src/main/paradox/docs/additional-info/architecture/use-cases.md
  src/main/paradox/docs/additional-info/architecture/use-cases.png
  src/main/paradox/docs/additional-info/benchmarks/data-volume-and-scenarios.md
  src/main/paradox/docs/additional-info/benchmarks/deployment-configuration.md
  src/main/paradox/docs/additional-info/benchmarks/index.md
  src/main/paradox/docs/additional-info/benchmarks/results.md
  src/main/paradox/docs/additional-info/index.md
  src/main/paradox/docs/additional-info/sdk.md
  src/main/paradox/docs/additional-info/sdk/img/nexus-js-logo.png
  src/main/paradox/docs/faq.md
  src/main/paradox/docs/getting-started/index.md
  src/main/paradox/docs/getting-started/running-nexus/index.md
  src/main/paradox/docs/getting-started/webapps.md
  src/main/paradox/docs/getting-started/webapps/img/clone-query.png
  src/main/paradox/docs/getting-started/webapps/img/copy-token.gif
  src/main/paradox/docs/getting-started/webapps/img/create-organization-button.png
  src/main/paradox/docs/getting-started/webapps/img/create-organization.png
  src/main/paradox/docs/getting-started/webapps/img/create-project-button.png
  src/main/paradox/docs/getting-started/webapps/img/create-project.png
  src/main/paradox/docs/getting-started/webapps/img/create-resource-button.png
  src/main/paradox/docs/getting-started/webapps/img/create-resource.png
  src/main/paradox/docs/getting-started/webapps/img/edit-organization-button.png
  src/main/paradox/docs/getting-started/webapps/img/edit-organization.png
  src/main/paradox/docs/getting-started/webapps/img/edit-project-button.png
  src/main/paradox/docs/getting-started/webapps/img/edit-project.png
  src/main/paradox/docs/getting-started/webapps/img/es-query-button.png
  src/main/paradox/docs/getting-started/webapps/img/es-query.png
  src/main/paradox/docs/getting-started/webapps/img/list-orgs.png
  src/main/paradox/docs/getting-started/webapps/img/list-projects.png
  src/main/paradox/docs/getting-started/webapps/img/list-resources.png
  src/main/paradox/docs/getting-started/webapps/img/login-web.png
  src/main/paradox/docs/getting-started/webapps/img/make-project-public.png
  src/main/paradox/docs/getting-started/webapps/img/new-query-button.png
  src/main/paradox/docs/getting-started/webapps/img/new-query.png
  src/main/paradox/docs/getting-started/webapps/img/search-resources.png
  src/main/paradox/docs/getting-started/webapps/img/sparql-query-button.png
  src/main/paradox/docs/getting-started/webapps/img/sparql-query.png
  src/main/paradox/docs/getting-started/webapps/img/view-resource.png
  src/main/paradox/docs/index.md
Labels: documentation, review

#557 Clarify Docker Swarm memory settings
  src/main/paradox/docs/architecture/meetup/img/EPFL_logo.svg
  src/main/paradox/docs/architecture/meetup/index.html
  src/main/paradox/docs/architecture/meetup/markdown
  src/main/paradox/docs/getting-started/running-nexus/docker-compose/docker-compose.yaml
  src/main/paradox/docs/getting-started/running-nexus/index.md
Labels: review

#548 Added AML2019 reference for the tutorials
  src/main/paradox/docs/tutorial/index.md
Labels: review

#560 👷‍♀️FIX: move EPFL logo to left for compliance reasons
  src/main/paradox/index.html
  src/main/product-page-src/index.html
Labels: frontend, review
